resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 20s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
                - org.springframework.web.client.ResourceAccessException
    instances:
      mainService:
        baseConfig: default

  ratelimiter:
    configs:
      default:
        timeoutDuration: 2000ms
        limitRefreshPeriod: 20000
        limitForPeriod: 5
    instances:
      mainService:
        baseConfig: default
